### ISSUE TITLE
eslint error: 'react-native/no-unused-styles': Set is not defined

### ISSUE THREAD

**Issue by ckoo7** [Intellicode/eslint-plugin-react-native#11]
Eslint terminated with this error
![screenshot from 2016-02-12 16-40-00](https://cloud.githubusercontent.com/assets/8359963/13005355/7817a16e-d1a7-11e5-9bba-7f428c57e865.png)

**Comment by Intellicode** [comment]
Hi @ckoo7,

Thanks for reporting this, could you share which version of Node you are using?

**Comment by Intellicode** [comment]
@ckoo7,

I'm closing this issue for now, feel free to open with more details
