### ISSUE TITLE
Plugin broke when updating to eslint 2.0

### ISSUE THREAD

**Issue by anback** [Intellicode/eslint-plugin-react-native#12]
Here is error and version information

![image](https://cloud.githubusercontent.com/assets/2440382/13042128/d943b38e-d3bd-11e5-9483-ffab84b2dc73.png)

![image](https://cloud.githubusercontent.com/assets/2440382/13042132/e38bd2ea-d3bd-11e5-8d24-f0efcb3f0011.png)

**Comment by Intellicode** [comment]
Cheers for the report, I didn't realise ESLint 2.0.0 was released already. Let me fix that for you :)

**Comment by Intellicode** [comment]
@anback can you try version 1.0.0?

**Comment by Intellicode** [comment]
@anback Feel free to open an issue again if you still experience issues with ESLint 2.0.0. Closing this for now.
