### ISSUE TITLE
UNMET PEER DEPENDENCY eslint@3.17.0

### ISSUE THREAD

**Issue by vovkasm** [Intellicode/eslint-plugin-react-native#133]
eslint-plugin-react-native 2.3.0 now requires eslint 3.12.1 to be installed on project (`peerDependencies`). But latest commits clear about real required version of eslint, it should be 3.17.0 (as in `devDependencies`).

Seems like greenkeeper.io bot ignores `peerDependencies`.

**Comment by StevePotter** [comment]
@vovkasm  I submitted a PR for this.   Please upvote it.  @Intellicode can you look at it?

**Comment by Intellicode** [comment]
@vovkasm Should be fixed now. @StevePotter thanks for your PR. Sorry for the issue! I guess we can't blindly use greenkeeper :)

**Comment by vovkasm** [comment]
Thank you!

**Comment by StevePotter** [comment]
No problem have a great day
