### ISSUE TITLE
Support eslint v4

### ISSUE THREAD

**Issue by michaelgmiller** [Intellicode/eslint-plugin-react-native#158]
When installing with eslint@4.0.0, I get:
npm WARN eslint-plugin-react-native@2.3.1 requires a peer of eslint@^3.17.0 but none was installed.

**Comment by Intellicode** [comment]
I'm planning to update as soon as my dependencies are also compatible with eslint 4.0.0, so far there are a few that are not compatible yet.

**Comment by noamokman** [comment]
Whats missing?

**Comment by Intellicode** [comment]
Basically, I'm using eslint-plugin-airbnb to lint the plugin itself, but it might not be worth it anymore to use it since it delays quickly updating to newer versions.

**Comment by kelset** [comment]
Airbnb [just released](https://github.com/airbnb/javascript/issues/1447#issuecomment-317335861) a new version, 15.1.0, that supports v4 - is there any other dependency you are waiting on? Would a PR help? Can't wait to test the new eslint :3

**Comment by ljharb** [comment]
@Intellicode nothing wrong with letting a new major version of eslint bake for a little while :-p

**Comment by Intellicode** [comment]
@kelset done!

@bspaulding, I had trouble getting your unit tests with regex options to work with the new eslint plugin, so please let me know if I broke something!

**Comment by sibelius** [comment]
any progress on this?

**Comment by sibelius** [comment]
`react-native/no-inline-styles` is working on v4

`react-native/no-unused-styles` is not

**Comment by Intellicode** [comment]
@sibelius can you provide details?

**Comment by sibelius** [comment]
it started working again, I restarted my webstorm

**Comment by bspaulding** [comment]
@Intellicode Sorry I just saw this notification, just updated to eslint 4 with 3.1.0 of this, LGTM. 👍
