### ISSUE TITLE
Set is not defined

### ISSUE THREAD

**Issue by danielbuechele** [Intellicode/eslint-plugin-react-native#16]
When running on circle-ci I get:
```
ReferenceError: Error while loading rule 'react-native/no-unused-styles': Set is not defined
```
I guess this might come from the usage of `new Set()` here: https://github.com/Intellicode/eslint-plugin-react-native/blob/master/lib/rules/no-unused-styles.js#L58
Can we add `es6-set` as dependency or use `babel-runtime`? I found a similar issue on this project: https://github.com/benmosher/eslint-plugin-import/issues/41

**Comment by Intellicode** [comment]
@danielbuechele Which version of Node are you running? Currently the project requires Node 4 (same as React Native) and according to my Travis build, it should work without problems.

**Comment by danielbuechele** [comment]
Ok, CircleCI is using node 0.10.33 by default. LOL
But I can set it up to use node > 4. So we can close this. Sorry for the confusion.

**Comment by Intellicode** [comment]
No problem!
