### ISSUE TITLE
Extends a recommended set of rules for native ?

### ISSUE THREAD

**Issue by ianjohnspain** [Intellicode/eslint-plugin-react-native#17]
Hi,

I was checking over at the react plugin (non native) and I notice they offer some extending which sets up a recommended config. 

`"extends": ["eslint:recommended", "plugin:react/recommended"]`

I was wondering if something exists in this plugin also ?

Thanks

**Comment by Intellicode** [comment]
Nope, but this is a good suggestion, I'll have a go at it when I have a bit more free time, but feel free to submit a PR for this feature as well!
