### ISSUE TITLE
Headers still get error "no-undef"

### ISSUE THREAD

**Issue by LRFILE** [Intellicode/eslint-plugin-react-native#191]
my code like:
option: {
    method: 'POST',
    headers: new Headers({
      'X-Api-Key': 'xxxxxxxxxxxxxxxx',
      'Content-Type': 'application/json'
    })
  }

then eslint tell me "no-undef" at Headers

**Comment by Intellicode** [comment]
Hi @LRFILE, I think you are in the wrong repo
