### ISSUE TITLE
Added in default node_modules

### ISSUE THREAD

**Issue by MohamadKh75** [Intellicode/eslint-plugin-react-native#194]
I want to configure the default node_modules when I use:

    react-native init NAME

Every time I use init command, I see a `eslint-plugin-react-native` package is installed by default!

I tried to uninstall it globally but no difference!

    npm uninstall -g eslint-plugin-react-native

How I can remove a package from default packages?

**Comment by Intellicode** [comment]
Hi @MohamadKh75, it is a dependency of react-native itself so thats why its installed by default.
