### ISSUE TITLE
a11y linting

### ISSUE THREAD

**Issue by alex-saunders** [Intellicode/eslint-plugin-react-native#199]
This project currently includes eslint-plugin-jsx-a11y for (mostly) web-oriented accessibility linting. Would the project also consider an eslint plugin for (specifically) react native accessibility? This project: https://github.com/FormidableLabs/eslint-plugin-react-native-a11y has just launched and I think it would be a great addition.

Would be interested to hear what you think!

**Comment by Intellicode** [comment]
Hi @alex-saunders, I'm definitely open to this. The plugin you mentioned was only included due to the fact that it was a peer dependency of eslint-plugin-airbnb I believe, so its only a dev dependency. How would you like to include the a11y plugin? I'm also open to merging the two plugins, to save React Native developers from an extra dependency.

**Comment by alex-saunders** [comment]
Hey @Intellicode , sorry about the slow reply on this, I got super busy this past month.

I was thinking that react-native-a11y would fit as an extension of the `all` config that this plugin provides. 

I.e:
```
all: {
      plugins: ['react-native', 'react-native-a11y'],
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      rules: allRulesConfig,
      extends: ['plugin:react-native-a11y/recommended'],
    },
```

If you can think of a more appropriate way to include the plugin, I'm open to suggestions!

**Comment by alex-saunders** [comment]
Hey @Intellicode ,

I totally understand why you'd be concerned over extending the config. My thinking was that if a developer has spefically defined that they want to use the `all` config from `eslint-plugin-react-native` then they would want every eslint rule that may be applicable to react native development, including accessibility.

How would this work if `eslint-plugin-react-native-a11y` was a peer dependency? Would eslint error if a developer used the `all` config without also downloading `eslint-plugin-react-native-a11y`?

**Comment by Intellicode** [comment]
@alex-saunders That's true, it's not an out-of-the-box experience that way. Without the plugin, it will crash. However, that makes me think the config should live somewhere else, for example in a config like eslint-config-airbnb or similar that provide recommended configs accross plugins. I guess we should do that or merge code bases.

**Comment by alex-saunders** [comment]
@Intellicode Good point, perhaps as eslint config project would be better suited to adopt `eslint-plugin-react-native-a11y`, I'll look into which projects might benefit from it!
