### ISSUE TITLE
sort-styles has a problem with detecting computed property names

### ISSUE THREAD

**Issue by MeenaAlfons** [Intellicode/eslint-plugin-react-native#213]
Example Usage:
<img width="241" alt="screen shot 2019-01-24 at 20 15 20" src="https://user-images.githubusercontent.com/5175706/51699248-ee3e3600-2014-11e9-950a-986b41abc220.png">

Error:
<img width="506" alt="screen shot 2019-01-24 at 20 15 43" src="https://user-images.githubusercontent.com/5175706/51699260-f72f0780-2014-11e9-8175-98e7eede78f7.png">

While using explicit property names works fine:
<img width="237" alt="screen shot 2019-01-24 at 20 17 46" src="https://user-images.githubusercontent.com/5175706/51699735-2eea7f00-2016-11e9-9859-2cf935b9d1ba.png">

**Comment by shirohana** [comment]
I have the same problem here (´-ωก`)

I'm creating a PR to fix it now
