### ISSUE TITLE
sort-styles does not work with export default

### ISSUE THREAD

**Issue by MeenaAlfons** [Intellicode/eslint-plugin-react-native#214]
Seems like `sort-styles` rule does not work with `export default`. See the example:

<img width="516" alt="screen shot 2019-01-24 at 20 43 43" src="https://user-images.githubusercontent.com/5175706/51700869-c81a9500-2018-11e9-81ce-72bbb8436af1.png">

**Comment by draperunner** [comment]
I'll take a look at this!

**Comment by karlmarxlopez** [comment]
I'm still experiencing this issue on `v3.8.1`
