### ISSUE TITLE
new rules idea: no-inline-styles, no-color-literals

### ISSUE THREAD

**Issue by aarongreenwald** [Intellicode/eslint-plugin-react-native#23]
Thanks for this plugin, these are useful rules. 

I think it would be nice to be able to detect inline styles in components and either warn/error when detected. We prefer style objects over littering the components with object literals with styles in them.

(There are cases where inline styles are appropriate, like when they use props/state and aren't available outside the render method. These would be exceptions to the rule.)

I've been working on this rule a bit, if it's something you'd accept I'd be happy to send a PR. Thanks!

**Comment by aarongreenwald** [comment]
And tacking on to the no-inline-styles idea is a no-color-literals rule, something we use on the web with sass. Color definitions should be stored in variables so they can be reused throughout the application and updated easily instead of scattered throughout the stylesheets. 

I am working on this one as well, both rules are working locally for me but I'd have to do some more cleanup before sending a PR.

**Comment by Intellicode** [comment]
Hi @aarongreenwald,

Sounds good, looking forward to your PR!

**Comment by Intellicode** [comment]
Hi @aarongreenwald, I just released a beta which includes your PR changes, please try it, I promote it to a full release if no one complains in a week!

**Comment by aarongreenwald** [comment]
@Intellicode Awesome, thanks! I'll use it and suggest that others do as well :)
