### ISSUE TITLE
no-raw-text should allow providing own custom text components

### ISSUE THREAD

**Issue by burtek** [Intellicode/eslint-plugin-react-native#239]
We have a Text-based wrapper component called `ProjectText`. There is currently no way of providing that to the rule.

**Comment by Ashwin-Mothilal** [comment]
I was also searching the same thing but for now, I solved like this `"react-native/no-raw-text": [2, { skip: "ProjectText" }]`

**Comment by burtek** [comment]
How did I miss that option? 🤦‍♂ Thanks mate
