### ISSUE TITLE
Error: Definition for rule 'react-native/no-inline-styles' was not found

### ISSUE THREAD

**Issue by eladcandroid** [Intellicode/eslint-plugin-react-native#25]
My .eslintrc file:

> {
  "parserOptions": {
      "ecmaVersion": 7,
      "sourceType": "module",
      "ecmaFeatures": {
          "jsx": true,
      }
  },
   "env": {
        "browser": true,
        "node": true
    },
  "plugins": [
    "react",
    "react-native"
  ],
 "extends": ["eslint:recommended", "plugin:react/recommended"],
 "rules": {
    "react-native/no-unused-styles": 2,
    "react-native/split-platform-components": 2,
    "react-native/no-inline-styles": 2,
    "react-native/no-color-literals": 2,
    "no-console":0,
    "no-alert":0
  },
  "settings": {
    "react": {
      "pragma": "React",
      "version": "15.1.0"
    }
  },
  "globals": { "fetch": false }
}

**Comment by Intellicode** [comment]
Did you install the plugin locally while running eslint globally?

**Comment by jasonmerino** [comment]
I'm trying to get this setup this morning and running into the same issue. I am running the local ESLint along with a local `eslint-plugin-react` and this `eslint-plugin-react-native`. 

My `.eslintrc` file looks like this.

```json
{
  "parser": "babel-eslint",
  "plugins": [
    "react-native",
    "react"
  ],
  "ecmaFeatures": {
    "jsx": true,
    "destructuring": true,
    "arrowFunctions": true,
    "classes": true,
    "objectLiteralShorthandMethods": true,
    "spread": true
  },
  "rules": {
    "arrow-parens": ["error", "always"],
    "arrow-spacing": ["error", { "before": true, "after": true }],
    "comma-dangle": [2, "always-multiline"],
    "comma-spacing": ["error", { "before": false, "after": true }],
    "complexity": ["error", { "max": 25 }],
    "eqeqeq": 2,
    "indent": ["error", "tab",{"SwitchCase": 1}],
    "jsx-quotes": 2,
    "no-console": ["error", {"allow": ["warn", "error"]}],
    "no-const-assign": "error",
    "no-debugger": 2,
    "no-dupe-args": 2,
    "no-multi-spaces": 2,
    "no-unused-vars": 2,
    "no-use-before-define": 2,
    "no-var": "error",
    "object-shorthand": ["error", "always"],
    "prefer-template": "error",
    "quotes": [2, "single"],
    "react-native/no-inline-styles": "error",
    "react/display-name": 0,
    "react/jsx-boolean-value": [0, "always"],
    "react/jsx-curly-spacing": 1,
    "react/jsx-no-duplicate-props": 1,
    "react/jsx-no-undef": 1,
    "react/jsx-sort-prop-types": 0,
    "react/jsx-sort-props": 0,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/no-danger": 1,
    "react/no-did-mount-set-state": 0,
    "react/no-did-update-set-state": 1,
    "react/no-multi-comp": 2,
    "react/no-unknown-property": 1,
    "react/prop-types": 2,
    "react/react-in-jsx-scope": 1,
    "react/require-extension": 1,
    "react/self-closing-comp": 2,
    "react/sort-comp": 2,
    "react/wrap-multilines": 2,
    "semi": 2,
    "space-before-blocks": ["error", { "functions": "always", "keywords": "always", "classes": "always" }]
  },
  "env": {
    "node": true
  },
  "globals": {
    "fetch": true
  }
}
```

And here's the versions of all the ESLint dependencies from my `package.json`.

```json
    "babel-eslint": "^6.0.0",
    "eslint": "^2.5.1",
    "eslint-plugin-react": "^4.2.3",
    "eslint-plugin-react-native": "^1.0.2",
```

Any help with this would be awesome. I'm going to try some other versions of this plugin to see if that changes anything.

**Comment by Intellicode** [comment]
@eladcandroid @jasonmerino please try to use the previous version (eslint-plugin-react-native-1.0.2), I will investigate the issue tonight

**Comment by Intellicode** [comment]
@eladcandroid @jasonmerino please have a look at https://github.com/Intellicode/eslint-react-native-example. I have tried and tested the configurations. The problem is that:
```  "react-native/no-inline-styles": "error",``` is not part of any version installed by`^1.0.2` but is part of `1.1.0-beta` which is not considered since its a pre-release. If you want to have access to the rule, you should define `1.1.0-beta` in your dependency. I will make an official release for it soon.

**Comment by anton-mladenov** [comment]
as of 2020 you can do this:
`rules: {
    "react-native/no-inline-styles": 0,
  },
}`

**Comment by ThevinMalaka** [comment]
> as of 2020 you can do this:
> `rules: { "react-native/no-inline-styles": 0 } }`

It's worked for me. Thank you very much.
