### ISSUE TITLE
Crashing when using style prop that is a string

### ISSUE THREAD

**Issue by DanielRamosAcosta** [Intellicode/eslint-plugin-react-native#278]
Here is the crashing error:

```
ESLint: 7.20.0
TypeError: Cannot read property 'type' of undefined
Occurred while linting /myuser/myapp/src/screens/Walkthrough.tsx:82
    at JSXAttribute (/myuser/myapp/node_modules/eslint-plugin-react-native/lib/rules/no-single-element-style-arrays.js:40:35)
    at /myuser/myapp/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/myuser/myapp/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/myuser/myapp/node_modules/eslint/lib/linter/node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (/myuser/myapp/node_modules/eslint/lib/linter/node-event-generator.js:285:22)
    at NodeEventGenerator.enterNode (/myuser/myapp/node_modules/eslint/lib/linter/node-event-generator.js:299:14)
    at CodePathAnalyzer.enterNode (/myuser/myapp/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /myuser/myapp/node_modules/eslint/lib/linter/linter.js:954:32
    at Array.forEach (<anonymous>)
```

This is caused because the [StatusBar component from Expo](https://docs.expo.io/versions/latest/sdk/status-bar/) has a style prop that can be `auto`, `inverted`, `light`, or `dark`. Here is the snippet where is crashing:

```tsx
<StatusBar style="light" backgroundColor={COLORS.PRIMARY[500]} animated />
```

This, is not:

```tsx
<StatusBar style={"light"} backgroundColor={COLORS.PRIMARY[500]} animated />
```

**Comment by jaquinocode** [comment]
Same exact problem for me. Through trial and error I figured out that the bad rule that does this is:
`react-native/no-single-element-style-arrays`

It also says the same in your error message.

**Comment by AndrePM** [comment]
As a __temporary workaround__ you could assign the style string to a variable:
```js
const statusBarStyle = 'light';
```
and then use that as your style:
```jsx
<StatusBar style={ statusBarStyle } />
```
This will prevent `eslint` from crashing. The ofc you will get the `react/style-prop-object` rule error, but you can fix this by adding `StatusBar` as an exception in your rules.

**Comment by AlanSl** [comment]
The good news: this was fixed in this PR https://github.com/Intellicode/eslint-plugin-react-native/pull/262 which was merged in March 2021 https://github.com/Intellicode/eslint-plugin-react-native/commit/b908186ee3f4171c3e53deb1634e6831d61e0516

The bad news: the last release, 3.10.0, was in September 2020.

@Intellicode can you please publish a patch release to NPM? Thanks!

**Comment by Intellicode** [comment]
@AlanSl, just made a release, hope it works! If it breaks let me know.

**Comment by AlanSl** [comment]
@Intellicode Thanks! 3.11.0 works fine for me, looks like this (and the two linked duplicates) are fixed 🎉

**Comment by Intellicode** [comment]
@AlanSl thanks for your confirmation!
