### ISSUE TITLE
How do i disable it?

### ISSUE THREAD

**Issue by amankumar6** [Intellicode/eslint-plugin-react-native#279]
I am working on a project as the project is in the beginning phase so we are using inline styles, when will we began the main development we will change the inline styles to components. 

I am annoyed to see the Eslint warning for writing inline styles how can I disable it?

I tried this in ```.eslintrc.js```, but it didn't work. 

```
module.exports = {
  root: true,
  extends: '@react-native-community',
  rules: {
    'no-inline-styles': 0,
  },
};
```

**Comment by FDiskas** [comment]
'no-inline-styles': 'off',
