### ISSUE TITLE
Support for browser-like globals

### ISSUE THREAD

**Issue by machadogj** [Intellicode/eslint-plugin-react-native#38]
React Native ships with some polyfills that mimic the interface from browsers (ie: setInterval, clearInterval, Geolocation API, etc...). It would be cool to have these in react-native to avoid using env: browser: true.

**Comment by Intellicode** [comment]
Let me see what I can do, I agree these would be nice to have.

**Comment by koenpunt** [comment]
Would be nice, yes!

**Comment by koenpunt** [comment]
This list should be sufficient I think: https://github.com/facebook/react-native/blob/master/.eslintrc#L19-L52

**Comment by MaxAggedon** [comment]
Any update on this ?

**Comment by Intellicode** [comment]
Hi @MaxAggedon unfortunately not, but I'll be happy to accept a PR for this!

**Comment by maxaggedon** [comment]
@Intellicode thanks for the answer, I will try to look into it if I find the time.

**Comment by Intellicode** [comment]
Should be fixed in 3.2.1
